package exp.images;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;

import org.apache.commons.codec.binary.Base64;
import org.apache.commons.io.IOUtils;

public class Image64EncoderDecoder {

	public static void decoder(Path imagePath, String imageString) throws IOException {
		// ByteArrayInputStream imageByteArray = new
		// ByteArrayInputStream(Base64.decodeBase64(imageString.getBytes()));

		byte[] imageByteArray = Base64.decodeBase64(imageString.getBytes());

		Files.write(imagePath, imageByteArray, StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
	}

	public static void encode(Path imagePath) throws IOException {

		byte[] imageByteArray = Files.readAllBytes(imagePath);

		String imageString = Base64.encodeBase64String(imageByteArray);

		System.out.println(imageString);
	}

	public static void encodeIS(Path imagePath) throws IOException {

		Base64 base64 = new Base64();

		InputStream inputStream = Files.newInputStream(imagePath, StandardOpenOption.READ);

		byte[] byteArray = IOUtils.toByteArray(inputStream);

		System.out.println(base64.encodeAsString(byteArray));
	}

	public static void main(String[] args) throws IOException {

		Path imagePath = Paths.get("Y:/MIFID_II/MIFID2_Reports/src/main/jasper/bilder/RGB(0,0,255).jpg");
		encode(imagePath);
//		encodeIS(imagePath);

//		String imageString = "iVBORw0KGgoAAAANSUhEUgAAAzMAAABFCAIAAADxWi+gAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAylSURBVHhe7dZn17ZHVYBh/pwgIkhVQOlVEFSK9N47AhZApShI770TkpCE0AkkoUQjSCCQQKTzhb3W3Nfzzjr3fmcygx/PtY4fcdziDz51fe+W53eroT9Mbv3pkT9KblP54+S2ldudueDkTy74Edy+c4fzu+PhTr3PnNw5ucvhTyt/drjrmQtP7ta5e/Lnh7843KN30ck9D/c63PuiH2f3Odz3Yrrf4f6dBxwe+NmTByUP7vzl4SGXnDz08FeVh116Q/Pww18f/qbyt5edPOLwyMOjDo/+3Dl/d3jM4bGHx11eePzlNzZPODzx8ydPOjy585QvnDz18LTD0w/P+OI5zzznJ82zvnTy7MNzOs/98snzDs8/vODwwq+c86LDiw8v+epPm5dW/v5rJy87vPzwiitO/qHzj4d/uuKm5p+/fvLKw6t63zh59eFfDv965cm/dV5zeO1V/wevO7z+6nP+/fAfhzd8k954+M9vnfOmb/2sefPhLd8+eWvlbd85efvhHWeuOXnnNT8/867Du8/818l7Du/tvO+/6f2HD1xb+OC1v2g+dOZ/Tj58+EjvuycfPXws+fj3zvnE934Jnzzzvyefqnz6cMH36TO9604uvO5XcFHl4h/QZ5NLfli4NLnszPWFz13/a7j8zI/O+fz5faH045Mvnt+Xhr58Q/abM185v6+WbqSv3TxXZD+5Wb6+6BvZT397c1z5/+GqgZvWXP37cWbkzJyZM3NmjTNzZs4ssGUhJayEeE2xZSElrIRj7eHGeuleY5jWKmdGzsyZOTNn1jgzZ+bMAlsWUsJKiNcUWxZSwko41h5urJfuNYZprXJm5MycmTNzZo0zc2bOLLBlISWshHhNsWUhJayEY+3hxnrpXmOY1ipnRs7MmTkzZ9Y4M2fmzAJbFlLCSojXFFsWUsJKONYebqyX7jWGaa1yZuTMnJkzc2aNM3NmziywZSElrIR4TbFlISWshGPt4cZ66V5jmNYqZ0bOzJk5M2fWODNn5swCWxZSwkqI1xRbFlLCSjjWHm6sl+41hmmtcmbkzJyZM3NmjTNzZs4ssGUhJayEeE2xZSElrIRj7eHGeuleY5jWKmdGzsyZOTNn1jgzZ+bMAlsWUsJKiNcUWxZSwko41h5urJfuNYZprXJm5MycmTNzZo0zc2bOLLBlISWshHhNsWUhJayEY+3hxnrpXmOY1ipnRs7MmTkzZ9Y4M2fmzAJbFlLCSojXFFsWUsJKONYebqyX7jWGaa1yZuTMnJkzc2aNM3NmziywZSElrIR4TbFlISWshGPt4cZ66V5jmNYqZ0bOzJk5M2fWODNn5swCWxZSwkqI1xRbFlLCSjjWHm6sl+41hmmtcmbkzJyZM3NmjTNzZs4ssGUhJayEeE2xZSElrIRj7eHGeuleY5jWKmdGzsyZOTNn1jgzZ+bMAlsWUsJKiNcUWxZSwko41h5urJfuNYZprXJm5MycmTNzZo0zc2bOLLBlISWshHhNsWUhJayEY+3hxnrpXmOY1ipnRs7MmTkzZ9Y4M2fmzAJbFlLCSojXFFsWUsJKONYebqyX7jWGaa1yZuTMnJkzc2aNM3NmziywZSElrIR4TbFlISWshGPt4cZ66V5jmNYqZ0bOzJk5M2fWODNn5swCWxZSwkqI1xRbFlLCSjjWHm6sl+41hmmtcmbkzJyZM3NmjTNzZs4ssGUhJayEeE2xZSElrIRj7eHGeuleY5jWKmdGzsyZOTNn1jgzZ+bMAlsWUsJKiNcUWxZSwko41h5urJfuNYZprXJm5MycmTNzZo0zc2bOLLBlISWshHhNsWUhJayEY+3hxnrpXmOY1ipnRs7MmTkzZ9Y4M2fmzAJbFlLCSojXFFsWUsJKONYebqyX7jWGaa1yZuTMnJkzc2aNM3NmziywZSElrIR4TbFlISWshGPt4cZ66V5jmNYqZ0bOzJk5M2fWODNn5swCWxZSwkqI1xRbFlLCSjjWHm6sl+41hmmtcmbkzJyZM3NmjTNzZs4ssGUhJayEeE2xZSElrIRj7eHGeuleY5jWKmdGzsyZOTNn1jgzZ+bMAlsWUsJKiNcUWxZSwko41h5urJfuNYZprXJm5MycmTNzZo0zc2bOLLBlISWshHhNsWUhJayEY+3hxnrpXmOY1ipnRs7MmTkzZ9Y4M2fmzAJbFlLCSojXFFsWUsJKONYebqyX7jWGaa1yZuTMnJkzc2aNM3NmziywZSElrIR4TbFlISWshGPt4cZ66V5jmNYqZ0bOzJk5M2fWODNn5swCWxZSwkqI1xRbFlLCSjjWHm6sl+41hmmtcmbkzJyZM3NmjTNzZs4ssGUhJayEeE2xZSElrIRj7eHGeuleY5jWKmdGzsyZOTNn1jgzZ+bMAlsWUsJKiNcUWxZSwko41h5urJfuNYZprXJm5MycmTNzZo0zc2bOLLBlISWshHhNsWUhJayEY+3hxnrpXmOY1ipnRs7MmTkzZ9Y4M2fmzAJbFlLCSojXFFsWUsJKONYebqyX7jWGaa1yZuTMnJkzc2aNM3NmziywZSElrIR4TbFlISWshGPt4cZ66V5jmNYqZ0bOzJk5M2fWODNn5swCWxZSwkqI1xRbFlLCSjjWHm6sl+41hmmtcmbkzJyZM3NmjTNzZs4ssGUhJayEeE2xZSElrIRj7eHGeuleY5jWKmdGzsyZOTNn1jgzZ+bMAlsWUsJKiNcUWxZSwko41h5urJfuNYZprXJm5MycmTNzZo0zc2bOLLBlISWshHhNsWUhJayEY+3hxnrpXmOY1ipnRs7MmTkzZ9Y4M2fmzAJbFlLCSojXFFsWUsJKONYebqyX7jWGaa1yZuTMnJkzc2aNM3NmziywZSElrIR4TbFlISWshGPt4cZ66V5jmNYqZ0bOzJk5M2fWODNn5swCWxZSwkqI1xRbFlLCSjjWHm6sl+41hmmtcmbkzJyZM3NmjTNzZs4ssGUhJayEeE2xZSElrIRj7eHGeuleY5jWKmdGzsyZOTNn1jgzZ+bMAlsWUsJKiNcUWxZSwko41h5urJfuNYZprXJm5MycmTNzZo0zc2bOLLBlISWshHhNsWUhJayEY+3hxnrpXmOY1ipnRs7MmTkzZ9Y4M2fmzAJbFlLCSojXFFsWUsJKONYebqyX7jWGaa1yZuTMnJkzc2aNM3NmziywZSElrIR4TbFlISWshGPt4cZ66V5jmNYqZ0bOzJk5M2fWODNn5swCWxZSwkqI1xRbFlLCSjjWHm6sl+41hmmtcmbkzJyZM3NmjTNzZs4ssGUhJayEeE2xZSElrIRj7eHGeuleY5jWKmdGzsyZOTNn1jgzZ+bMAlsWUsJKiNcUWxZSwko41h5urJfuNYZprXJm5MycmTNzZo0zc2bOLLBlISWshHhNsWUhJayEY+3hxnrpXmOY1ipnRs7MmTkzZ9Y4M2fmzAJbFlLCSojXFFsWUsJKONYebqyX7jWGaa1yZuTMnJkzc2aNM3NmziywZSElrIR4TbFlISWshGPt4cZ66V5jmNYqZ0bOzJk5M2fWODNn5swCWxZSwkqI1xRbFlLCSjjWHm6sl+41hmmtcmbkzJyZM3NmjTNzZs4ssGUhJayEeE2xZSElrIRj7eHGeuleY5jWKmdGzsyZOTNn1jgzZ+bMAlsWUsJKiNcUWxZSwko41h5urJfuNYZprXJm5MycmTNzZo0zc2bOLLBlISWshHhNsWUhJayEY+3hxnrpXmOY1ipnRs7MmTkzZ9Y4M2fmzAJbFlLCSojXFFsWUsJKONYebqyX7jWGaa1yZuTMnJkzc2aNM3NmziywZSElrIR4TbFlISWshGPt4cZ66V5jmNYqZ0bOzJk5M2fWODNn5swCWxZSwkqI1xRbFlLCSjjWHm6sl+41hmmtcmbkzJyZM3NmjTNzZs4ssGUhJayEeE2xZSElrIRj7eHGeuleY5jWKmdGzsyZOTNn1jgzZ+bMAlsWUsJKiNcUWxZSwko41h5urJfuNYZprXJm5MycmTNzZo0zc2bOLLBlISWshHhNsWUhJayEY+3hxnrpXmOY1ipnRs7MmTkzZ9Y4M2fmzAJbFlLCSojXFFsWUsJKONYebqyX7jWGaa1yZuTMnJkzc2aNM3NmziywZSElrIR4TbFlISWshGPt4cZ66V5jmNYqZ0bOzJk5M2fWODNn5swCWxZSwkqI1xRbFlLCSjjWHm6sl+41hmmtcmbkzJyZM3NmjTNzZs4ssGUhJayEeE2xZSElrIRj7eHGeuleY5jWKmdGzsyZOTNn1jgzZ+bMAlsWUsJKiNcUWxZSwko41h5urJfuNYZprbnpt78Dji6O5/EF9h4AAAAASUVORK5CYII=";
//		Path newImagePath = Paths.get("C:/hermann/MIFID2/PageHeaderImage_new.png");

//		decoder(newImagePath, imageString);

//		encode(newImagePath);
//		encodeIS(newImagePath);

	}

}
